### ISSUE TITLE
 Silo level plugin parameters error

### ISSUE THREAD

**Issue by omakood** [motoz/PellMon#104]
0.7.1-alpha1
Copy-paste into calculate.conf:
```
calc1_prog = 50000 oldlevel gdef
 if magazine_content get oldlevel grcl > then
    magazine_content get silo_reset_level set
 end
 magazine_content get oldlevel gsto
calc1_taskcycle = 10
```
Gives error in every 10 seconds:
2020-12-16 20:27:15,564 - INFO - error in calc1_progunexpected end of program, No return value, stack is empty at 19 

Silo level changes to magazine level and is correct, only error fills up log.

**Comment by motoz** [comment]
It's been a while since I looked at this stuff... but I think the error message is telling you that there is no return value from the script. Well in this case there isn't a need for a return value (no-one will use it for anything), but the script is executed by reading it so you will get this error if there isn't something left on the stack after it's read (whatever is left on the stack by the script is the return value).

It *should* be fixed by just adding a number at the end, like e.g:

    calc1_prog = 50000 oldlevel gdef
     if magazine_content get oldlevel grcl > then
        magazine_content get silo_reset_level set
     end
     magazine_content get oldlevel gsto 1

**Comment by omakood** [comment]
It works now.
Thank You, great Python project!
