### ISSUE TITLE
owfs plugin sometimes reads an '!' character

### ISSUE THREAD

**Issue by jteg68** [motoz/PellMon#59]
Hi,

sometimes the owfs plugin reads an '!' character from owserver. This is likely due to some cabling issues. The effect is that the log window gets messages from the calculation plugin, about failed operations. As the errors seems to go away immediately there are no visible errors in the system picture.

The following diff of connection.py seems to avoid the '!` being used. I'm not sure the changes are correct or complete.

Comments?

Thanks,
Jörgen

````python
--- connection.py.dist	2015-02-01 19:03:02.014260446 +0100
+++ connection.py	2015-02-03 15:03:07.836475384 +0100
@@ -140,12 +140,13 @@
 
             ret, payload_len, data_len = self.unpack(data)
 
-            if payload_len >= 0:
+            if ret > 0 and payload_len >= 0:
                 data = s.recv(payload_len)
                 rtn = self.toNumber(data[:data_len])
                 break
             else:
                     # ping response
+                data = None
                 rtn = None
                 break
 
@@ -237,8 +238,8 @@
         payload_len  = socket.ntohl(val[1])
         try:
             ret_value    = socket.ntohl(val[2])
-        except OverflowError:
-            ret_value = 0
+        except:
+            return 0, -1, 0

         format_flags = socket.ntohl(val[3])
         data_len     = socket.ntohl(val[4])
         offset       = socket.ntohl(val[5])

**Comment by jteg68** [comment]
Crappy kybard.
Is it not possible to edit the title?

/Jörgen

**Comment by motoz** [comment]
Thanks for looking in to this, I have noticed something similar but I have not tried to debug it. Originally I used the ownet module since it is included in the debian repos but it didn't work very well. I think it didn't handle the owserver protocol pings at all or something similar so I included the whole package with pellmon and made a quick fix. 

I'll try to look into this sometime, but ownet seems to be quite old and unmaintained, maybe we could switch to https://pypi.python.org/pypi/pyownet/0.8.0 instead?

**Comment by jteg68** [comment]
pyownet looks more complete. I'll give it a try in the weekend

**Comment by jteg68** [comment]
No good progress with a pyownet plugin due to lack of time and python experience.
There are still times when the owfs plugin reads clearly incorrect values like a basement temperature of -600 C. To avoid alarms on those situations I made a simple 'inside' function with perameters low and high, and sends an alarm mail if the temp is between -1 and 16C. Works for me sofar.

I couldn't get a if/then/else/end to work. How about an example in the docs?

**Comment by motoz** [comment]
Are you sure the spikes are not caused by the owserver misreading the sensors due to cabling problems and disturbances? That seems to be very common. Checking the logs I have one single "c2_prog error: 'min' at 4: could not convert string to float" error for the last couple of weeks, where a calculate script errored out because the value returned by ofws was not a number. I think this is because of ownet flakiness, but I don't think it's the same thing when it does return a number but with a strange value. 

Here is an example I used to check that 'if then else end' does still work, c3_prog is written with '2' when 'c2_prog' is nonzero, else '3' :
```
c1_prog = if c2_prog get then 2 c3_prog set else 3 c3_prog set end
c1_taskcycle = 1
c1_progtype = R/W

c2_prog = 0
c2_readitem = v1
c2_progtype = R/W

c3_prog = 0
c3_readitem = v2
c3_progtype = R/W
```

**Comment by motoz** [comment]
The branch feature/pyownet has pyownet instead of ownet but not much tested. Reading temp sensors seems to work. I have no idea if writing and ds2406 latches work as don't have anything connected to test with now. I had trouble with pyownet 0.8.0 so you might need 0.8.1 as released the other day.

**Comment by jteg68** [comment]
The errors most likely come from cabling errors. With the change in the top the errors of type '!' went away but I still got one -600 temp reading. One in two weeks, that is.
I'm now running your pyownet code with a trivial change to round the numbers. I like to see my decimal zeros! :)  So far so good.
Thanks!

**Comment by motoz** [comment]
I pushed a branch 'feature/onewire_filter' where you can set a median filter on onewire readings with window length 3 to 21. In theory a three point median filter completely eliminates errors affecting only one sample, but since the owserver caches values I suppose it is possible to get a whole row of the same misread value. But maybe you could check it out if it helps?

**Comment by motoz** [comment]
Pyownet has now replaced ownet in v0.1.0
