### ISSUE TITLE
Right y-axis does not show in the trend window

### ISSUE THREAD

**Issue by jteg68** [motoz/PellMon#60]
Hi,

adding a line 
d01 = 0.0:2.0
to the [scaling] section gives a nicely scaled signal but the y-axis on the right side is not shown. Is this the intended behaviour? I expected to see a separate axis here.

/Jörgen

**Comment by motoz** [comment]
There was a right side y-axis when the chart was rendered server side by rrdtool, but since the switch to client side rendering with flothcharts that's gone. Rrdtool has an option to scale the right side axis which was used to match it with the scaled data but flotchars has nothing similar so I just dropped that for the moment.

With flotcharts however there could be any number of y-axes and the data would not have to be prescaled by the rrdtool export when the axes are set up, but nothing is implemented yet. Some config option should be implemented for adding axes to the chart. 

I actually removed the comment about right axis scaling from the config file last week in commit b9ecf71caf620569bb99508b3624e512578520ba

**Comment by jteg68** [comment]
Further the value shown in the trend at the pointer is not scaled back to its original value.

**Comment by motoz** [comment]
I'll leave this as an enhancement request to add support for several y-axes to the chart. The scaling option could remain but it would be mostly useless, unless the data in the database for some reason needs to be scaled before viewing. In that case the chart popup value should show the scaled value and not the original value.

**Comment by motoz** [comment]
The won't ever be done so I'm closing it.
