### ISSUE TITLE
Data in the system picture drops a decimal zero

### ISSUE THREAD

**Issue by jteg68** [motoz/PellMon#61]
Hi,

in the system picture float numbers like 73.0 is shown as 73 while 73.1 is shown as 73.1. Possibly this is coming from the owfs side, I didn't check yet.
This is not a big deal but a small annoyance to the eye as the numbers move a bit when changing between say 72.9 and 73.1.

/Jörgen

**Comment by motoz** [comment]
This is by design, I don't want every value like kg and % readings showing up with a trailing zero decimal. A possible improvement would be to add a format string specifier to the paramname:item syntax to allow for arbitrary formatting of the data. 

The stripping of the trailing zero happens in the changeSystemImageText function in https://github.com/motoz/PellMon/blob/master/src/Pellmonweb/media/js/index.js, a better design would be to do the rounding server side. OWFS temperature data with lots of decimals are constantly changing and transmitted to the client only to be rounded to the old value.

**Comment by jteg68** [comment]
Agreed.
Made a round function for the calculate plugin to test rounding in the server and having the client show all digits. It seems to work but it's annoying to have to write calculations for each value in the system image. A better design would be needed for this to be practical.

**Comment by motoz** [comment]
Probably won't ever be done
