### ISSUE TITLE
Controlling 1-wire IO

### ISSUE THREAD

**Issue by Flygarkatt** [motoz/PellMon#70]
Just got a project up and running where I plan to controll pumps and other items based on data from temperature sensors.
What I need is how to controll IO on a DS2413 and DS2408 from input and calculations.

/Bqt

**Comment by motoz** [comment]
The DS2413 is controller by writing 1 or 0 to PIO.A  or PIO.B for the second switch. There are several possible ways to achieve what  you want.

First you need to set up an item for the switch in the OWFS plugin, eg:

    ow2413_path = 12.8D3E7D000000/PIO.A
    ow2413_type = R/W
    ow2413_item = ow2413out

Now you can open the switch by writing '0' to the **ow2413out** item and close it by writing '1'.

To control the switch from some temperature reading you could call the  command line client pellmoncli from eg a cron job:

    pellmoncli set ow2413 1

will close the switch

To read your temperature item from pellmoncli, use the **get** command:
    
    pellmoncli get mytemp

Another way is to use the ***calculate*** plugin, where you can set up a periodic task to read a temperature item and write to the output item depending on the condition you choose. For instance this wil close the switch when mytempitem is > 65:

    calc1_prog = mytempitem get 65 > ow2413 set
    calc1_taskcycle = 10

And the third way would be to make your own pellmon plugin which would give the most possibilities, if you decide to go this way then i recommend using the 0.7.0 beta (or newer) since the plugin interface is radically simpler than the latest release.

**Comment by Flygarkatt** [comment]
Many thanks,
I´ll test asap and post the results
/Bqt

**Comment by motoz** [comment]
How's it going with your project?

**Comment by Flygarkatt** [comment]
http://213.65.28.38:8081/
Ungefär


Mvh / Pär B
På rörlig fot


-------- Originalmeddelande --------
Från: Anders Nylund
Datum:2016-09-22 11:31 (GMT+01:00)
Till: motoz/PellMon
Kopia: Pär Bergqvist , Author
Rubrik: Re: [motoz/PellMon] Controlling 1-wire IO (#70)


How's it going with your project?

**Comment by motoz** [comment]
Ser bra ut, jag cencurerade din IP ovan tillsvidare, du borde nog ändra lösenordet så att ingen börjar styra dina grejer från nätet...

**Comment by Flygarkatt** [comment]
Hej igen,

Calculate, korta frågor:
* Hur hög är stacken? 4 värden?
* "if .. then .. [else] .. end" men fungerar även "if .. then .. else .. else .. [elseif] .. end"?
* case .. then, finns den med?

Kort sagt, vilket språk.

mvh /Bqt
----------------------------------
Incedo Teknik AB
Pär Bergqvist
070 - 352 18 70
________________________________
Från: Anders Nylund [notifications@github.com]
Skickat: den 22 september 2016 12:00
Till: motoz/PellMon
Kopia: Pär Bergqvist; Author
Ämne: Re: [motoz/PellMon] Controlling 1-wire IO (#70)


Ser bra ut, jag cencurerade din IP ovan tillsvidare, du borde nog ändra lösenordet så att ingen börjar styra dina grejer från nätet...

**Comment by motoz** [comment]
I'll answer in English to keep the info more generally useful.

The 'calculate' stack is a python list, ie. limited only by memory. There are no checks so it will generate a python exception and fail when you push too much (like many millions...)

The 'calculate language' is exactly as the documentation says in the default config file, ie there is no 'elseif' and only one (optional) else.

The code implementing the _calculate_ **if then [else] end** construct is here: https://github.com/motoz/PellMon/blob/master/src/Pellmonsrv/plugins/calculate/__init__.py#L200
