### ISSUE TITLE
sorry, i´m new to this all

### ISSUE THREAD

**Issue by jorau** [motoz/PellMon#72]
Hi,

sorry, i´m sure this is not the right way to contact you ....
I´ve got a raspberry and don´t know how to connect this one to my scotte NBE 6.77 ...
Shall i simply pull wires from the gpio to the grnd/tx/rx on the NBE?
And than tx to rx or rx to rx?
Many thanks in advance

**Comment by motoz** [comment]
Hello, this is absolutely a good way to ask questions

You _can_ use the build in serial port on the raspberris GPIO pins 8 and 10 (if I remember correctly). But it's not very easy and you can not connect the raspberry directly to the scotte controller by wiring tx to rx and rx to tx. The reason is that the scotte controller outputs much more voltage on the tx pin than the raspberry's gpio is designed for. So you need to build, or buy, a voltage converter to sit between them to protect the raspberry. The raspberry is also configured to use the serial port as a system terminal, so you need to reconfigure it for general use.

A much easier way is to use a usb to serial converter. You might have heard that most of the cheap ones does not work very well in windows, but they all seem to work with no problems at all in linux so I would really recommend you do that. Then you just need to wire tx in the usb-serial port (pin 3) to rx in the controller and rx (pin 2) to tx and gnd (pin 5) to gnd.

**Comment by jorau** [comment]
Thank you for the fast response.
Good I didn´t try it on my own ;o)
Since I´ve never used such a usb to serial, do you mean something like this?
![ttl-232rg-vip-we_sml](https://cloud.githubusercontent.com/assets/24354878/20860381/00b4251c-b977-11e6-89c3-37231ec972c7.jpg)
or could you provide me a link to see exactly which converter I need?
Again, thanks for your time.

**Comment by motoz** [comment]
That's likely not the correct type. The converter should provide a serial port that has the same voltage levels (rs-232 levels) as the 9 pin serial port found on all old pc:s. Like one of these http://www.ftdichip.com/Products/Cables/USBRS232.htm

**Comment by jorau** [comment]
In your link, the wire-ended converter differ in the "additional voltage output level", does this matter?
I´m from germany, here there seem just to exist models with the connector, should i take such an converter and cut off the conncetor?

**Comment by motoz** [comment]
No, does not matter for this application. The one you linked looks fine.

**Comment by jorau** [comment]
Hi again, got my converter and installed it, seems to work. 
Now I´ve another question, if I´ll use pellmoncli with cron to control the burners "worktime", do I have to disable the controllers time-table?
Thank You again for your project and your answers.

**Comment by motoz** [comment]
I have never used the build in scheduling functions in the burner controller so I don't really know for sure,  but I don't see why you couldn't still us that for what it does while sending commands to eg. start and stop the burner from cron with pellmoncli. If the burner is shut off by a command from pellmoncli then I would suspect that the build in scheduling will be disabled until it is started again, but it's hard to know without testing.
