### ISSUE TITLE
Updated to 0.7.0, strange things happens in calculate plugin.

### ISSUE THREAD

**Issue by Flygarkatt** [motoz/PellMon#76]
This section in calculate.conf:
calc1_prog = if solar_feed get 4 - accbott_temp get > then 0 cirkpump_solar set end if solar_feed get accbott_temp get < then 1 cirkpump_solar set end
calc1_taskcycle = 10
Suddenly gives this event:
"2017-06-19 14:58:43,704 - INFO - error in calc1_progunexpected end of program, No return value, stack is empty at 24" each cycle.

/Bqt

**Comment by motoz** [comment]
Did you recently update? This is probably a new 'feature' of the calculate script engine. 
Since a script could be executed on reading an item it should have a return value, and that return value will be whatever is left on the stack when the script is finished. In this case no one needs any return values but it still complains (yeah, bug or 'feature'). Anyway you can silence it simply by leaving something on the stack, eg add a zero or something to the script (after the last end) then then it will become the return value and the error should go away.

**Comment by Flygarkatt** [comment]
Recently updated, yes.
Added a "0" after last "end" helped. Thanks for that.

Next simple question: when using "min" or "max on the stack and the values are equal, e.g. "1" "1".
Takes one of them or drops an error?

**Comment by motoz** [comment]
You get the maximum/minimum, not error.
