### ISSUE TITLE
Control an output with a Button in PellmonWeb

### ISSUE THREAD

**Issue by mogber** [motoz/PellMon#91]
Hi motoz.
I would like to make the extra button: "Control an output with a Button in PellMonWeb", as Motoz describes it. However, I have trouble getting started due to my (yet) little knowledge about this.

Should the text strings, beginning with the "(plugin_Calculate) copy" be copied to the folder: /home/pi/PellMon/etc/pellmon/conf.d/plugins, or should a new page be created?

Should the following be used only for onewire solution ?:
[Plugin_RaspberryGPIO]
btn1gpio_function = output
btn1gpio_item = button1output
# Use GPIO4, pin 7
btn1gpio_pin = 7

regards mogber

**Comment by motoz** [comment]
Hello mogber,

short answer: yes you should copy all of it into the configuration file for the calculate plugin:
`/etc/pellmon/conf.d/plugins/calculate.conf`

Or the slightly longer answer: It doesn't matter at all in which configuration file any piece of configuration is, as long as it is found by pellmon. Pellmon reads all of them and appends the contents of all .conf files into one big configuration, and only then starts to interpret the contents. This means that the configuration could be in one big file and it would work the same, it actually was that way a couple of years ago but it grew too big to handle so I decided to split up the default configuration in "kind of" logical groups to make it (slightly) easier to find things. Any file with extension .conf below /etc/pellmon is used as part of the configuration.

The last part in the example configuration starting with `[Plugin_RaspberryGPIO]` is for controlling an output pin on a raspberry pi, if you want to control a onewire output instead you skip that part and make something similar instead for the `OWFS` plugin.

Hope this makes it clearer, if not just ask again...

**Comment by mogber** [comment]
Hello Anders

 

Thank you very much for your answer. I think I have done as described, but it does not appear to be installed properly. I have attached a picture of the texts I have copied into the two config folders. The attached log shows that there are errors in plugin dirs, but I do not know what's wrong.

Hope you can take me on.

 

Sincerely Mogens (mogber)

**Comment by motoz** [comment]
You can't unfortunately add pictures to the issue using the email interface to reply, instead you should go to https://github.com/motoz/PellMon/issues/91 and reply to the issue using the web interface, where you can add images by dragging them into the comment box.

**Comment by mogber** [comment]
Hello Anders

Thank you very much for your answer. I think I have done as described, but it does not appear to be installed properly. I have attached a picture of the texts I have copied into the two config folders. The attached log shows that there are errors in plugin dirs, but I do not know what's wrong.
Hope you can take me on.

Sincerely Mogens (mogber)

![calculate plugin config](https://user-images.githubusercontent.com/36407246/36980929-a3eccc56-2083-11e8-949d-8b406320d1d5.PNG)
![raspberrygpio config](https://user-images.githubusercontent.com/36407246/36980935-abbed168-2083-11e8-826b-9f1e0c7f97b0.PNG)
![log](https://user-images.githubusercontent.com/36407246/36980940-b0a582bc-2083-11e8-8f68-700d065b0854.PNG)

**Comment by motoz** [comment]
You already closed the issue, but I'm answering anyway in case it was by mistake. 

You have not activated the plugins you are using; 'Calculate', and 'RaspberryGPIO'.To enable them, edit the file /etc/pellmon/conf.d/enabled_plugins.conf.

Plugins are enabled by listing them in the [enabled_plugins] section in the configuration, the standard plugins are already listed in the enabled_plugins.conf file, but most of them are disabled on a standard installation by having their activation rows commented away. Remove the comment character '#' in front of the row that lists the plugin you want to use.

(The log message 'invalid setting for plugin_dirs' can be ignored, the setting is disabled by default and the error is because the setting doesn't exist. My mistake...)

**Comment by mogber** [comment]
I've closed the subject by mistake!

I'm not yet fully in line with the task. In the log, two lines are now written, first: "Looking for plugins in /usr/lib/phyton2.7/dist-packages/Pellmonsrv/plugins."

And later: “Activated plugins. ScotteCom, SiloLevel, Consumption, Cleaning.”

But I still can’t see the button anywhere . Where should it pop up?

**Comment by motoz** [comment]
Did you try to enable the two plugins you want to use for this, 'Calculate' and 'RaspberryGPIO'?
When you have them enabled you should see a line in the log like this:
`Activated plugins. ScotteCom, SiloLevel, Consumption, Cleaning, Calculate, RaspberryGPIO`

**Comment by motoz** [comment]
The button shows up under the 'Calculate' menu, in the Parameters view. Just like the 'Clean' button under the 'Cleaning' menu.

**Comment by mogber** [comment]
Thank you for reopening, and your reply. 
I see now that Calculate, RaspberryGPIO is missing in my log. 
I will try once again. 

![log](https://user-images.githubusercontent.com/36407246/37044876-ecac9c78-2164-11e8-87b6-b48cb9212374.PNG)

**Comment by mogber** [comment]
I cant figure what's wrong, I have now attached the "enabled" file, with my changes.

![enabled_plugins conf](https://user-images.githubusercontent.com/36407246/37046790-73120542-2169-11e8-93a5-d7033b82974d.PNG)

**Comment by motoz** [comment]
I don't know, it looks ok to me. I suppose you have restarted pellmon or rebooted the raspberry after the change?

Just to try something you could try to disable eg. the 'Cleaning' plugin and verify that it gets disabled.

**Comment by mogber** [comment]
Yes, the PI vas restarted several times.  
I have tried to disable the 'Cleaning' plugin and it became not disabled.
I have also tried to install the button on a security disk, with the same negative result
I wonder if there is an error in my pellmon installation, or may bee I do something else wrong.

**Comment by motoz** [comment]
How did you install pellmon? .deb file or from source?

Are you sure you are editing the correct file, and that you really  are saving the changes? If  you have commented out the row where the cleaning plugin is enabled, and it still is enabled after that, then I can't see any other way that could happen than you are somehow editing the wrong file. Note that you must have root access rights to be able to change the configuration file.

Run this in a terminal to verify that you have edited the correct file:

    cat /etc/pellmon/conf.d/enabled_plugins.conf

An easy way to edit the configuration is to use pellmons build in web-based configuration editor `pellmonconf `as described in https://github.com/motoz/PellMon/wiki/How-to-install-PellMon

**Comment by mogber** [comment]
Hello Anders.
For me it looks like the settings are not come thru, wright?


![plugin dirs](https://user-images.githubusercontent.com/36407246/37105521-ac969406-222f-11e8-9958-f827e0dddce5.PNG)

**Comment by motoz** [comment]
No idea, you only showed me the end of the file. Maybe you could scroll a bit up where you made the changes?

**Comment by mogber** [comment]
Oh, it went too fast for me. I can now see that the changes have not come into force, presumably because I have corrected in the files, instead of in the LXterminal.
Sorry for taking your time.

mogber

![enabled plugins](https://user-images.githubusercontent.com/36407246/37122275-28fee41e-2260-11e8-8993-46745cefb67f.PNG)

**Comment by motoz** [comment]
You don't tell me much about how you are trying to edit the configuration files, but I think what you are missing is that you need to start the program you are using to edit the changes with 'root' rights. Otherwise you are not allowed to save your changes.

In the terminal you use the command 'sudo' to gain root rights, as showed in the 'how to install pellmon' link I gave above. One option is to use the text editor 'nano' in the terminal, another is to use 'pellmonconf' which works in a web-browser.

Have you tried to use pellmonconf? That should be the absolutely most easy way to edit the pellmon configuration files if you are not familiar with linux.

![pellmonconf](https://user-images.githubusercontent.com/3408131/37136895-27ca95f6-22ac-11e8-835f-380b6c00b85a.png)

**Comment by mogber** [comment]
Now it works. 
The fault was that I corrected the files inside the folder structure. Now I have used LXterminal, and installed the two files there, and finally enabled them. 
I didn’t use “pellmonconf” because I only, now and then, is able to open http://localhost:8083, and then again only some of them. Fault text: ”Unable to connect to this site”. I don’t know why jet.
But again, thank you for your patience with a beginner.
with best regards
Mogens
![button1](https://user-images.githubusercontent.com/36407246/37154987-fb20c8be-22e1-11e8-8d66-c474ff36e43b.PNG)

**Comment by motoz** [comment]
Great!

Some background info to help you understand what's going on:

First, pellmonconf is not a background service, you need to start it in a terminal, and have it running while you use it. If you close it with ctrl-C, or if you close the terminal window, it will shut down.

Second, when you say 'corrected the files inside the folder structure', I have to read between the lines to figure out what you really mean. You can't edit the files anywhere else, they are where they are inside the folder structure.

But you probaly mean that you navigated to the files using a graphical file browser program (similar to the file explorer in windows, or finder in mac) and there doubleclicked the files to open them in a program suitable for handling them.

Since those files are plain text files they open in a graphical text editor. So far so good, but you are now running the graphical editor as the logged in user, eg. the **'pi'** user. A normal user (like 'pi') is not allowed to change system files, only view them, so you can't save the changes.

To be able so save the changes you have to run the text editor, be it a graphical program or in the teminal, as **'root'** user. It's possible to start the graphical file manager as 'root' (eg by starting it from the terminal with 'sudo'), then you can navigate to a system file, and open it in the text editor as root by double-clicking  but it's **not** recommended since it's so easy to mess up the system.

**Comment by mogber** [comment]
Thanks again. 

Now I understand a lot more. You ”read between the lines”  exactly as I did it.
