### ISSUE TITLE
Problems reading any data from serial interface

### ISSUE THREAD

**Issue by syastrov** [motoz/PellMon#93]
This is perhaps outside the scope of PellMon, but I cannot seem to read any data from the pellet controller box.
I have a Scotte box with a 6.79 chip.
I have bought a PL2303HX usb-to-serial adapter and connected the GND to GND and TX to RX, RX to TX.
It is connected to a Raspberry Pi 3 B.

pellmon.log:
```
2018-04-20 23:17:45,615 - INFO - Timeout again, give up and return fail
2018-04-20 23:17:47,757 - INFO - Timeout again, give up and return fail
2018-04-20 23:17:49,762 - INFO - Timeout again, give up and return fail
2018-04-20 23:17:51,767 - INFO - Timeout again, give up and return fail
2018-04-20 23:17:53,772 - INFO - Timeout again, give up and return fail
2018-04-20 23:17:54,772 - INFO - error in retry [Errno 0] GetItem failed
```

Haven't been able to establish any connection.
However, the /dev/ttyUSB0 device appears in lsusb
```Bus 001 Device 009: ID 067b:2303 Prolific Technology, Inc. PL2303 Serial Port```

What could the problem be?
I measured 3.5V from TX to GND across the PL2303HX wires.
On the Scotte terminals, I got a reading of -6.5 V from TX to GND.
Does that have any significance?

Am I using totally the wrong usb2serial adapter or is the wiring incorrect?

Thanks for the nice software.
I am myself a programmer but don't have a lot of hardware experience.
I look forward to using it once I get a working connection!

**Comment by motoz** [comment]
I think you might have the wrong usb-serial adapter. [Here](http://www.prolific.com.tw/US/ShowProduct.aspx?p_id=8&pcid=41) it's described as 'rs232 like' interface, and in other places it's sold as "USB To RS232 TTL UART PL2303HX", where TTL means that the voltage levels are in the range 0..5V instead of (about) -12..+12V which is required by the RS232 specification. The one you have is probably meant for a connection that uses the same protocol as the serial bus informally called  RS232, but that doesn't actually use the same voltage levels. (These are often sold without the male 9-pin DSUB connector).

You need something like [this](https://www.amazon.com/Sabrent-Serial-Adapter-Chipset-CB-FTDI/dp/B006AA04K0/ref=pd_lpo_vtph_tr_img_2?_encoding=UTF8&psc=1&refRID=BMT43Q119XMW5Z4HNT2S&dpID=41Vot6RyZyL&preST=_SY300_QL70_&dpSrc=detail) (Just the first google result for rs232 serial adapter...) And a  also a [serial cable](https://www.amazon.com/Tripp-Lite-Straight-Extension-P520-006/dp/B000067SBO/ref=sr_1_6?s=electronics&ie=UTF8&qid=1524296858&sr=1-6&keywords=232+cable) which you cut and strip the wires to connect it to the controller.

You can also have a look at the old stokerkontrol [guide](http://www.stokerkontrol.dk/index.php?page=rs232&lang=uk) for connecting a pc to the controller. (The 'chip' mentioned should already be installed, it's the TTL-RS232 level converter chip (eg MAX232) that's needed to connect to an RS232 serial port. In theory you could get your existing serial adapter to work if you remove that chip and bridge the right pins where the chip has been, since now you have the same TTL levels in both ends, but that's not something I recommend if you don't have hardware experience and are willing to maybe destroy the burner controller...)

Hope this helps, feel free to ask more questions if needed.

**Comment by syastrov** [comment]
Thanks for the response. I think I will go buy that rs232 adapter + serial cable and try it out.

**Comment by syastrov** [comment]
I got it up and running with the adapter + cable. 👍
Thanks for the help!
