### ISSUE TITLE
Pellmon losing time

### ISSUE THREAD

**Issue by Flygarkatt** [motoz/PellMon#96]
Hi,
It seems as Pellmon is having hard to keep time compared to the RPi.
Always a gap whem rebooting.
![image](https://user-images.githubusercontent.com/21130884/42395819-82b19106-815f-11e8-8cc5-aae0298ffb5c.png)

BR
/Bqt

**Comment by motoz** [comment]
I suppose you use a ramdisk for the database? Pellmonsrv tries to catch the SIGTERM signal and store the database on reboot, but that doesn't seem to work anymore. Maybe things have changed with the systemd conversion in jessie. When the power is abruptly cut this is of course the expected result.

**Comment by Flygarkatt** [comment]
Hm,
Same happens if USB stick mounted as drive then?
Let's dive into Raspian and see what they´ve done :-)

**Comment by motoz** [comment]
Well if you have configured pellmonsrv to write the database to ram then it will lose everything since the last copy to nonvolatile storage. The copy interval can also be configured, I think the default is every second hour to save the sd card. If you have the database on a drive that can handle writing every 30 second, then there is no need to use a ramdisk. This signal handler was supposed to handle the copy on soft reboot https://github.com/motoz/PellMon/blob/3e2511ada9e2cd5715c5c9ad67f45a41ef8d82f3/src/Pellmonsrv/pellmonsrv.py#L345
