### ISSUE TITLE
Unable to connect to NBE V13 burner

### ISSUE THREAD

**Issue by Freezerz** [motoz/PellMon#98]
I've connected the burner (WOODY BS+ 16 KW) to my wifi, and am able to ping it's IP, and also the IP of the provided Android tablet (the controlling unit for the burner).

However neither nbetest nor PellMon are able to find it/connect to it.
For nbetest, "client.py parameters get info" will tell me "socket.timeout: timed out" regardless of providing IP/password or not in place of "parameters".

In PellMon I've disabled ScotteCom, and enabled NBECom, and provided the serial number and password of the burner in the respective config file.
I've tried both the precompiled version, and building it myself from source as per the README file.
PellMon output looks like this:
wait controller
wait controller
wait controller
wait controller
wait controller
find controller retry 0 timeout('timed out',)
wait controller
wait controller
wait controller
wait controller
wait controller
find controller retry 1 timeout('timed out',)
wait controller
wait controller
wait controller
wait controller
wait controller
find controller retry 2 timeout('timed out',)
wait controller
wait controller
wait controller
wait controller
wait controller
find controller retry 0 timeout('timed out',)

I don't know if it's important or not, but the output doesn't contain the following two lines, as opposed to how it looks in this person's issue: https://github.com/motoz/PellMon/issues/78
get rsa 0
use rsa for xtea set 2377

I have installed pip and xtea and the other software packages specified in the README.

Using nmap I haven't been able to locate open ports on the burner, and Wireshark only discovers IGMPv2 packages sent from the burner IP to 224.0.0.1, which, as far as I can tell, are broadcast messages.

Wireshark also identifies that the Ubuntu PC with PellMon running, sends out UDP packets with contents along the line of "tr013NBE_DISCOVERY" to IP 255.255.255.255.

My burner is version 13.1005.9, and the app on the tablet is version 1.172.

Does anyone have any idea as to why I'm unable to connect to the burner, or what I should try to do to identify the problem? Has the protocol changed as the burner is only a couple of months old?

Any help/ideas are greatly appreciated.

**Comment by motoz** [comment]
There are some protocol changes in recent V13 versions so unfortunately it doesn't work, not with pellmon nor nbetest. I have been in contact with NBE some time ago about this and I have been promised an updated protocol specification. It's probably no big deal to add support for the new protocol if I get the spec.

**Comment by Freezerz** [comment]
Thank you very much for that explanation.
Let me know if I can do anything to help when you get the protocol specification.

**Comment by motoz** [comment]
It doesn't look like we're ever going to get some more info from @stokersoft
In two months I only ever got this answer:

"There are slight differences, but the main protocol is identical.
For example the discovery response might be a bit different, as we included a model field. But he should see some response, as the request is the same."

So according to that you should see a response, but there is not much more we can do. It was fun while it lasted, I guess...

**Comment by stokersoft** [comment]
Hi,

A test controller is on its way that you can play with - sorry for delay on
that. The current public test controller is down for service, will probably
not come up again (too many custom wires for experiments). I add a new one
to the test setup.

I let you know when its available.

------
Jens Hyldahl
Stokersoft
Branddamsvej 2
8920 Randers NV
www.stokersoft.com
info@stokersoft.com



Den tor. 24. jan. 2019 kl. 17.59 skrev Anders Nylund <
notifications@github.com>:

**Comment by motoz** [comment]
Thank you for the response! Access to a public test controller would of course be nice but on it's own it will probably not help. If we can get some info of the protocol changes I think maybe @Freezerz can help debug the changes needed without the public test controller.

**Comment by Freezerz** [comment]
I'll be more than happy to help getting it to work, by testing the changed code against my burner.

**Comment by stokersoft** [comment]
Nice - test controller on its way today or tomorrow.

I will go through the api, and see how you can get a new updated
specification - allow me some time for that task.

------
Jens Hyldahl
Stokersoft
Branddamsvej 2
8920 Randers NV
www.stokersoft.com
info@stokersoft.com



Den søn. 27. jan. 2019 kl. 12.13 skrev Freezerz <notifications@github.com>:

**Comment by stokersoft** [comment]
Hi guys

Find attached specification for the v13 controller. Its not complete, but
should be sufficient to get a good hold on it.

I have setup a test controller - you cant do any harm to it, its pure test:
serial: 31376
password: 6267931545

I will try to keep it running, but ping me if you find it unavailable. Its
installing now, give it 20 minutes before you try.

------
Jens Hyldahl
Stokersoft
Branddamsvej 2
8920 Randers NV
www.stokersoft.com
info@stokersoft.com



Den søn. 27. jan. 2019 kl. 12.13 skrev Freezerz <notifications@github.com>:

**Comment by motoz** [comment]
Thank you!
The attachment doesn't survive being sent through github's email notification system though, so could you visit github and attach it using the webui, or send it to my private email.

**Comment by motoz** [comment]
I got the protocol spec, but the only changes I can see is a couple of new function codes, so I have no idea why its not answering at all. The test controller seems to be firewalled, can you have a look into that @stokersoft ?

The protocol format is more or less like this, as can be seen from e.g. nbetest frames.py

| Request field    | bytes | Details                       |
|------------------|-------|-------------------------------|
| app_id           |    12 | string                        |
| controller id    |     6 | string                        |
| encrypted        |     1 | ' '=No, '*'=RSA, '-'=xtea     |
| start            |     1 | STX=2                         |
| function         |     2 | ascii function code number    |
| seqnum           |     2 | ascii sequence number         |
| pincode          |    10 | ascii, spaces when unencrypted|
| timestamp        |    10 | ascii seconds since 01.01.1970|
| extra            |     4 | future use                    |
| payloadsize      |     3 | ascii number                  |
| payload          |     n |                               |
| end              |     1 | EOT=4                         |

| Response  field  | bytes | Details                       |
|------------------|-------|-------------------------------|
| app_id           |    12 | string                        |
| controller id    |     6 | string                        |
| start            |     1 | STX=2                         |
| function         |     2 | ascii function code number    |
| seqnum           |     2 | ascii sequence number         |
| response code    |     1 |                               |
| payloadsize      |     3 | ascii number                  |
| payload          |     n |                               |
| end              |     1 | EOT=4                         |

| Function codes   | Function                |
|------------------|-------------------------|
|                0 | Discovery               |
|                1 | Read setup value        |
|                2 | Set setup value         |
|                3 | Read setup range        |
|                4 | Read operating data     |
|                5 | Read advanced data      |
|                6 | Read consumption data   |
|                7 | Read chart data         |
|                8 | Read event log          |
|                9 | Read info               |
|               10 | Read avail. programs    |

where function code 0 = discovery and 1=read setup data

My code sets appid and controller id to random strings, since at least the previous controller versions didn't mind.

I don't know how to debug this as long as it doesn't answer at all.

**Comment by stokersoft** [comment]
Hi,

Let me check the firewall tomorrow. You need to specify the correct serial
number, or it will be rejected in v13.

Also let me dump a succesful discovery request for inspiration.

I will be back.


------
Jens Hyldahl
Stokersoft
Branddamsvej 2
8920 Randers NV
www.stokersoft.com
info@stokersoft.com



Den tir. 5. feb. 2019 kl. 19.02 skrev Anders Nylund <
notifications@github.com>:

**Comment by motoz** [comment]
That's usef ful info, I added a --serial option to the nbetest client in the testing/v13 branch, @Freezerz can you check if that works?

**Comment by stokersoft** [comment]
What port are you connecting to? Still be back later.

ons. 6. feb. 2019 17.39 skrev Anders Nylund <notifications@github.com>:

**Comment by motoz** [comment]
8483

**Comment by stokersoft** [comment]
Ok, fine, please take a look at these request/responses:

DPpbqkqUqafb043084 000100000000000000000000pad 013NBE Discovery :
192.168.4.2:1901
DPpbqkqUqafb043084
00010065Serial=43084;IP=192.168.0.189;Type=v13std;Ver=1015;Build=2;Lang=0

the controller 31376 should be available on v7testbox.stokercloud.dk port
8483 for testing

Let me know if this helps :-)


------
Jens Hyldahl
Stokersoft
Branddamsvej 2
8920 Randers NV
www.stokersoft.com
info@stokersoft.com



Den ons. 6. feb. 2019 kl. 18.13 skrev Anders Nylund <
notifications@github.com>:

**Comment by motoz** [comment]
Thanks, but still no response. The only real difference I can spot is that I space padded the serial number instead of zero padding, but changing that didn't make any difference. I do get an icmp port unreachable though (as before).

This is the data part of the UDP frame I'm sending:
````
                                     20 20 61 65 65 68   Ú.àÑ!#.I´.  aeeh
0030   69 67 6b 66 63 68 30 33 31 33 37 36 20 02 30 30   igkfch031376 .00
0040   34 33 20 20 20 20 20 20 20 20 20 2d 31 35 34 39   43         -1549
0050   34 37 36 31 30 31 65 78 74 72 30 31 33 4e 42 45   476101extr013NBE
0060   5f 44 49 53 43 4f 56 45 52 59 04                  _DISCOVERY.
````

**Comment by Freezerz** [comment]
I've been trying a few things with nbetest and my own Ruby script, and now think there're two issues, as specified below.

### Issue 1 - figuring out the protocol
While trying to connect to the burner, I've managed to create a malformed UDP packet from a Ruby script, to which the burner actually responds.

Request looks like this (no start byte nor end byte and either wrong or correct serial number):
> 0000   b4 fb e4 2b 2b 82 00 26 55 b1 fd d2 08 00 45 00   ´ûä++..&U±ýÒ..E.
> 0010   00 5b f5 c7 40 00 40 11 c0 5f c0 a8 01 11 c0 a8   .[õÇ@.@.À_À¨..À¨
> 0020   02 09 ce b9 21 23 00 47 84 c3 44 50 70 62 71 6b   ..Î¹!#.G.ÃDPpbqk
> 0030   71 55 71 61 66 62 30 34 33 30 38 34 20 30 30 30   qUqafb043084 000
> 0040   31 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30   1000000000000000
> 0050   30 30 30 30 30 70 61 64 20 30 31 33 4e 42 45 20   00000pad 013NBE 
> 0060   44 69 73 63 6f 76 65 72 79                        Discovery

Response looks like this:
> 0000   00 26 55 b1 fd d2 b4 fb e4 2b 2b 82 08 00 45 00   .&U±ýÒ´ûä++...E.
> 0010   00 4f 11 6d 00 00 7f 11 a5 c6 c0 a8 02 09 c0 a8   .O.m....¥ÆÀ¨..À¨
> 0020   01 11 21 23 14 ac 00 3b a5 90 3a 44 50 70 62 71   ..!#.¬.;¥.:DPpbq
> 0030   6b 71 55 71 61 66 62 30 34 33 30 38 02 30 30 30   kqUqafb04308.000
> 0040   31 31 30 32 33 49 6c 6c 65 67 61 6c 20 73 74 61   11023Illegal sta
> 0050   72 74 20 63 68 61 72 61 63 74 65 72 04            rt character.

So there seems to actually be a connection to the burner service on port 8483, which is good news.

However if I send a request like the one below, it doesn't respond at all. I've tried with the correct serial number and with/without the password written on the label on the motherboard.

> 0000   b4 fb e4 2b 2b 82 00 26 55 b1 fd d2 08 00 45 00   ´ûä++..&U±ýÒ..E.
> 0010   00 5d c9 72 40 00 40 11 ec b2 c0 a8 01 11 c0 a8   .]Ér@.@.ì²À¨..À¨
> 0020   02 09 99 ec 21 23 00 49 84 c5 44 50 70 62 71 6b   ...ì!#.I.ÅDPpbqk
> 0030   71 55 71 61 66 62 30 34 33 30 38 34 20 02 30 30   qUqafb043084 .00
> 0040   30 31 30 30 30 30 30 30 30 30 30 30 30 30 30 30   0100000000000000
> 0050   30 30 30 30 30 30 70 61 64 20 30 31 33 4e 42 45   000000pad 013NBE
> 0060   20 44 69 73 63 6f 76 65 72 79 04                   Discovery.


### Issue 2 - port limitation?
Furthermore the request is sent from e.g. local port 52921 to remote port 8483, but the response from the burner is sent from remote port 8483 to local port 5292. The local port changes for each request, but the pattern is the same: It returns the response on the first four digits of the port only.
This seems strange, as I believe it should return the response to the same port number as the request originated from.
I've tried digging around, but haven't yet found any way to specify the source port in Ruby, so I can't force it to use a four digit port, but perhaps that is a possibility in Python?


### Protocol specification
Is there any chance for me to get a look at the protocol specification? I've tried as best as I can to use the information provided by motoz in a previous post, but the protocol specification could help in trying different types of requests.

**Comment by motoz** [comment]
Interesting, I pushed a change that binds the socket to the same port as it's sending to (8483). It suppose I would have to add some error checking also to verify that the port is free to use. It's easier to just let the stack get me a free one so I just did that previously. I still get no answer from the testbox, must be a firewall issue on the other side.

I can't post the whole spec, it says on the first row "CONFIDENTIAL INFORMATION - DO NOT DISTRIBUTE WITHOUT WRITTEN PERMISSION" but I'm sure you can get it from Stokersoft.

**Comment by motoz** [comment]
@stokersoft, did you check that you can reach the testbox from outside your network? Because whatever I send I only get an icmp port unreachable back. Something on your side has to send that frame and I suppose it can't be the actual controller.
![screenshot from 2019-02-08 18-12-48](https://user-images.githubusercontent.com/3408131/52490533-9d5e3e00-2bcd-11e9-9f77-67e9274aaa30.png)

**Comment by motoz** [comment]
No news... I also tried replicating the example discovery frame above exactly, with and without correct serial, only response is **port unreachable**

@Freezerz, you seem to have an extra space after the serial number in the frame with start and end bytes above:

    0030 71 55 71 61 66 62 30 34 33 30 38 34 *20* 02 30 30 qUqafb043084 .00

Did you try the nbetest commit with the response port set to same as request? There are some other differences between the example discovery frame and what nbetest does; password set to all zeros instead of space padded dash, real timestamp instead of zeroes, sequence number starting from 1 instead of randomized. I can't test if any of these matters myself since the testbox appears to be blocked.

**Comment by Freezerz** [comment]
Sorry about the wait time as I've been a bit busy lately, but this time I return with good news.

After finally getting around to testing further, it seems to work after your changes regarding specifying the controller ID in the request, and the source port being four digits.
I also managed to get my own script to send (bind) from a lot of different four digit ports, and that works as well.

So to sum up my findings.
Invalid request sent from four digit port: the boiler will respond with error message to same port.
Invalid request sent from five digit port: the boiler will respond with error message to port consisting of first four digits of source port.
Valid request sent from four digit port: the boiler will respond with corresponding response to same port.
Valid request sent from five digit port: the boiler will NOT respond.

@stokersoft, That should probably be fixed in the boiler software, to ideally work with five digit ports.


Regarding nbetest there seems to be a few issues remaining:
*Some of the get commands not being valid requests (info/sw_versions). It responds "Illegal payload size".
*The readme mentions -V parameter but it can't be used
*A few of the print statements doesn't use parenthesizes, so the script doesn't work out of the box with Python 3.6.5
Do you want that information in this thread, or would it be better with a new issue on nbetest?


I haven't tried raw or set, and will not do that until those functions have been tested thoroughly against the test controller, as I don't want to risk messing with my boiler.

**Comment by motoz** [comment]
I pushed a two commits to 'develop' that should fix the two issues: correct serial number sent in discovery, and port number below 9999, also some fixes in nbetest. Let me know if it works...

"get info" should return something if you have an active info message, otherwise probably nothing.

You could create an issue in nbetest (or better a pull request..). I didn't care that much about the whole nbetest, it was as the name says only for testing and familiarization with the protocol, but every now and then someone finds it useful so I suppose these should be fixed.

**Comment by stokersoft** [comment]
Hi All

The test controller is 31376 - i see you sent something to 43084 to
nbetestbox - that will definately not work, thats another controller behind
the firewall.

Also you have seen that 5 digit ports are troublesome - that is fixed in
latest beta version, i will update the controller in the next morning.

Do you still need me to check the firewall, if something is wrong?

------
Jens Hyldahl
Stokersoft
Branddamsvej 2
8920 Randers NV
www.stokersoft.com
info@stokersoft.com



Den man. 11. feb. 2019 kl. 19.53 skrev Anders Nylund <
notifications@github.com>:

**Comment by motoz** [comment]
Well as far as I know the testbox doesn't exist. Did you look at the wireshark screenshot above?

**Comment by stokersoft** [comment]
Hi,

I upgraded the controller 30016, it has some test firmware, that should be
fine, but might have caused some troubles.

The new one accepts any valid port (please try it)

I have reset the firewall rules and double checked and added once again.

Please try v13testbox.stokercloud.dk at port 8483 once again.

------
Jens Hyldahl
Stokersoft
Branddamsvej 2
8920 Randers NV
www.stokersoft.com
info@stokersoft.com



Den tir. 12. feb. 2019 kl. 07.40 skrev Anders Nylund <
notifications@github.com>:

**Comment by motoz** [comment]
Yes, now I have a response to the discovery frame (but from v7testbox, not v13testbox...), thanks!
It doesn't respond at all to a "read setup value" with payload "boiler.*" though...

Or actually, now I notice that it says in the discovery response "Serial=030016", and with that serial it does respond to a read setup value. Didn't you say that the V13 doesn't respond without the correct serial? Now it seems that it does respond to a discovery with any serial, just like the old V7?

I suppose you swapped the controller, in the beginning it was serial 31376. The password seems to have changed also, whats the password of the new box?

**Comment by motoz** [comment]
This is a new error I think, I responds with payload 'Illegal password' although payload size is zero, which makes the whole frame illegal according to my implementation.. 

```
0000   40 f0 2f ec 01 88 c0 4a 00 2c b8 76 08 00 45 00   @ð/ì..ÀJ.,¸v..E.
0010   00 48 8e 87 00 00 f4 11 e3 e6 b9 11 da 0b c0 a8   .H....ô.ãæ¹.Ú.À¨
0020   00 71 21 23 21 24 00 34 ea 38 20 20 64 63 69 6a   .q!#!$.4ê8  dcij
0030   6a 65 65 62 66 61 30 33 30 30 31 36 02 30 32 32   jeebfa030016.022
0040   38 31 30 30 30 49 6c 6c 65 67 61 6c 20 70 61 73   81000Illegal pas
0050   73 77 6f 72 64 04                                 sword.
```

**Comment by stokersoft** [comment]
Yes 31376 it is, sorry for confusion.

ons. 13. feb. 2019 14.54 skrev Anders Nylund <notifications@github.com>:

**Comment by motoz** [comment]
What? Now you're making me *really* confused.
I get an answer from 30016, but never one single bit back from any 31376.

But I don't have a working password for 30016.

**Comment by motoz** [comment]
Hello @stokersoft, still there??

**Comment by motoz** [comment]
@Freezerz @stokersoft , this is apparently going no further so If you don't have anything to add I'll just close this issue then. It might or might not work with the change I pushed ~6 weeks ago, I can't test it.

**Comment by stokersoft** [comment]
Hi Sorry - what do you need? The test controller should be running, if not
i will setup on another location, i can do that tuesday.

------
Jens Hyldahl
Stokersoft
Branddamsvej 2
8920 Randers NV
www.stokersoft.com
info@stokersoft.com



Den tor. 21. mar. 2019 kl. 08.36 skrev Anders Nylund <
notifications@github.com>:

**Comment by motoz** [comment]
Sorry if I have not been clear enough.

As I previously said I have never been able to get *anything* back from the controller you mean should be accessible, i.e. the one with serial number 31376. It is not accessible now nor has it ever been to my knowledge.

Another one with the serial number 30016 appeared briefly over a month ago (as I mentioned above) and then later disappeared. The password you gave me for the 31376 controller did of course not work for the 30016 controller.

As long as the 30016 controller was on line I was able to confirm that with the 4 digit port number change, reading settings seem to work, but I couldn't check changing settings as I don't have a password for it. Then I sort of gave up on this due to the silence, personally I have no use for supporting V13.

I also mentioned this error above: https://github.com/motoz/PellMon/issues/98#issuecomment-463272200
What do you think? Is it a new error or not? As I understand the protocol spec there should be no payload text in a frame where the payload size is set to zero, so my code ignores that frame as illegal. Of course I can special case that one in my code, but why even have the payload size in the frame if it must be ignored to be able to parse the frame?
